### ISSUE TITLE
category flag fails to filter all category pages

### ISSUE THREAD

**Issue by EternalMoment** [wikipedia2vec/wikipedia2vec#36]
Hey team,

I use the latest enwiki and train a model with the following cmd:
```
wikipedia2vec train enwiki-20190701-pages-articles.xml.bz2 enwiki-20190701-300d \
--dim-size=300 \
--no-lowercase \
--min-word-count=30 \
--min-entity-count=10
```
To my understanding, by default, the category flag is `False`. Therefore, it should filter all wiki category pages.

However, by examine the titles in the wikipedia2vec model, I found the following titles:
```
:Category:American actors
:Category:American architects
:Category:American film actors
...
```
categories are not fully filtered.

We could change the code [here](https://github.com/wikipedia2vec/wikipedia2vec/blob/3ea9b581673553bb580250e72b8af2278402b214/wikipedia2vec/dictionary.pyx#L201) by adding more filters and check if the title starts with `:Category:`.

In a similar fashion, you might also want to filter non-entity with title that starts with:
```
:wikt: 
:Category: 
:Image: 
:category: 
:commons: 
:Template: 
:File:
...
```
There are quite some suspicious non-entity title that starts with `:`

**Comment by EternalMoment** [comment]
Should I raise a PR for the change?

**Comment by ikuyamada** [comment]
Because of the varied syntax of MediaWiki, it is generally hard to filter out all categories.
Therefore, Wikipedia2Vec uses very simple string matching to filter out categories.
Further, I briefly checked the DumpDB and it seems that other types of pages (e.g., *File* pages and *Image*) except *Category*, *Module*, and *TimedText* are not contained in the DB.
Note that, the list of page types can be seen here: https://www.mediawiki.org/wiki/Template:Pagetype#Default_namespace_sets

Also, pull requests are always welcomed :)
